import os
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LAUNCHER = ROOT / "tools" / "local_demo_launcher.py"
ICON = ROOT / "tools" / "local_demo_icon.ico"
OUT_DIR = ROOT / "本地演示EXE"
BUILD_DIR = ROOT / ".pyinstaller-build"
SPEC_DIR = ROOT / ".pyinstaller-spec"
ONEDIR_DIST = BUILD_DIR / "dist-onedir"

EXE_NAMES = [
    "启动本地演示",
    "打开用户端",
    "打开后台端",
    "停止本地演示",
    "重启本地演示",
]

USAGE = """校园助手本地演示 EXE 使用说明

1. 推荐优先双击“启动本地演示.exe”。
   这是快速启动版无黑框图形控制台，可以查看本地服务状态，并启动、重启、打开用户端、打开后台端、打开日志目录。
   关闭这个控制台窗口时，会自动停止本地 8000/5173 服务，避免答辩结束后残留后台进程。

2. 如果想一步打开页面：
   双击“打开用户端.exe”，会显示同一个图形控制台，后台无黑框启动本地服务，并打开 http://127.0.0.1:5173/index.html。
   双击“打开后台端.exe”，会显示同一个图形控制台，后台无黑框启动本地服务，并打开 http://127.0.0.1:8000/studio/。
   页面打开后请保留控制台窗口；关闭控制台窗口即代表退出本地演示并停止本地服务。

3. 如果服务异常或想重新启动：
   双击“重启本地演示.exe”，会显示同一个图形控制台，先停止 8000/5173 端口上的本地演示进程，再重新启动并打开用户端。

4. 如果答辩结束：
   双击“停止本地演示.exe”，会静默停止本地后端和前端服务。

5. 日志位置：
   local-demo-logs/backend.stderr.log
   local-demo-logs/backend.stdout.log
   local-demo-logs/frontend.stderr.log
   local-demo-logs/frontend.stdout.log

注意：
这些 exe 依赖同目录下的 _internal 运行时目录，以及当前项目目录中的 .venv、backend、campus.db、app.js 等文件。
请不要只单独移动 exe；如果要换电脑演示，需要连同整个项目目录一起移动。
"""


def run(command: list[str]) -> None:
    print(" ".join(command))
    env = os.environ.copy()
    env["PYTHONUTF8"] = "1"
    env["PYTHONIOENCODING"] = "utf-8"
    subprocess.run(command, cwd=ROOT, env=env, check=True)


def main() -> int:
    if not LAUNCHER.exists():
        raise SystemExit(f"missing launcher: {LAUNCHER}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    SPEC_DIR.mkdir(parents=True, exist_ok=True)
    ONEDIR_DIST.mkdir(parents=True, exist_ok=True)

    for name in EXE_NAMES:
        target = OUT_DIR / f"{name}.exe"
        if target.exists():
            target.unlink()
    runtime_dir = OUT_DIR / "_internal"
    if runtime_dir.exists():
        shutil.rmtree(runtime_dir)
    source_dir = ONEDIR_DIST / EXE_NAMES[0]
    if source_dir.exists():
        shutil.rmtree(source_dir)

    command = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--clean",
        "--onedir",
        "--contents-directory",
        "_internal",
        "--windowed",
        "--noupx",
        "--log-level",
        "WARN",
        "--name",
        EXE_NAMES[0],
        "--distpath",
        str(ONEDIR_DIST),
        "--workpath",
        str(BUILD_DIR),
        "--specpath",
        str(SPEC_DIR),
    ]
    if ICON.exists():
        command.extend(["--icon", str(ICON)])
        command.extend(["--add-data", f"{ICON}{os.pathsep}tools"])
    command.append(str(LAUNCHER))
    run(command)

    if not source_dir.exists():
        raise SystemExit(f"missing PyInstaller output: {source_dir}")

    for item in source_dir.iterdir():
        destination = OUT_DIR / item.name
        if item.is_dir():
            shutil.copytree(item, destination, dirs_exist_ok=True)
        else:
            shutil.copy2(item, destination)

    launcher_exe = OUT_DIR / f"{EXE_NAMES[0]}.exe"
    if not launcher_exe.exists():
        raise SystemExit(f"missing launcher exe: {launcher_exe}")
    for name in EXE_NAMES[1:]:
        shutil.copy2(launcher_exe, OUT_DIR / f"{name}.exe")

    (OUT_DIR / "使用说明.txt").write_text(USAGE, encoding="utf-8")

    # Remove stale Tcl/Tk metadata generated by interrupted PyInstaller runs, if any.
    for leftover in [OUT_DIR / "__pycache__", BUILD_DIR / "__pycache__"]:
        if leftover.exists():
            shutil.rmtree(leftover)

    print(f"built fast onedir launcher and {len(EXE_NAMES)} exe entrypoints in {OUT_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
